version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Monta el directorio `app` en `/app` dentro del contenedor
    env_file:
      - .env  
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - .env  # Carga las variables necesarias para MySQL desde .env
    ports:
      - "3306:3306"


